### ISSUE TITLE
Twig runtime error: ("Undefined property: stdClass::$widget")

### ISSUE THREAD

**Issue by SimpleByDesign** [sojimaxi/grav-plugin-widget#8]
Twig runtime error on theme processing. I get the following error:

`Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Undefined property: stdClass::$widget")."`

When my template has the following code. It would appear to not like the fact that the block name is the same as the widget name.
```
      {% block footer %}
        {% if theme_config.footer.enabled %}
        <footer id="footer">
              {{ widget( 'footer' ) }}
        </footer>
        {% endif %}
      {% endblock %}
```

However if you rename the block as in the following code, the page renders correctly.

```
      {% block blockfooter %}
        {% if theme_config.footer.enabled %}
        <footer id="footer">
              {{ widget( 'footer' ) }}
        </footer>
        {% endif %}
      {% endblock %}
```

**Comment by SimpleByDesign** [comment]
I have to update that I hadn't cleaned down my cache after altering the theme code. After clearing the cache the following code brings out the same exception when I though it was working:

```
 {% block blockfooter %}
        {% if theme_config.footer.enabled %}
        <footer id="footer">
              {{ widget( 'footer' ) }}
        </footer>
        {% endif %}
      {% endblock %}
```

However I have discovered that if you add a widget location to the same page (you don't need to add an actual widget) and save the page. Visiting the page now renders correctly. 

It would appear that the global option of the plugin isn't being called or initiated on a page without a widget set on that page, however by adding at least a widget location to a page it would appear it forces the plugin to run.

**Comment by sojimaxi** [comment]
@SimpleByDesign I reviewed your codes on both issues and I realized what happened in your case. 
The plugin doesn't affect twig blocks in anyway. Firstly I think you should update the plugin.
If you change your defined widget areas in your theme from
```yaml
widget:
  areas: [...,footer,...]
```
to
```yaml
widget:
  areas: [...,widgetfooter,...]
```
you will need to update the reference for it as well in the page ` frontmatter` or `site.yaml` 
```yaml
widget:
  areas:
    -
      location:  footer #change to widgetfooter
      widgets:
       - .....
```
The location fields are auto populated from your theme definitions therefore the old locations defined will not be available and will mostly revert to `default` location while editing via the admin.

Also make sure to clear cache `bin/grav clear-cache` when done with the changes.
Everything should load up fine.

**Comment by sojimaxi** [comment]
Resolved in #7

**Comment by alexej-d** [comment]
@sojimaxi The error still persists. I have defined some areas in my theme.yaml like so:

```
widget: 
  areas: [aside,footer]
```
Then I defined some global widgets and put them in those areas. Running `widget('aside')` or `widget('footer')` in a twig template gives me then the same twig runtime error as above.

If I add the following to every page front matter, the error disappears:
```
widget:
    areas:
        -
            location: default
```

**Comment by sojimaxi** [comment]
@alexej-d thanks for reporting this. Did you try the fix reported here?  [#7](https://github.com/sojimaxi/grav-plugin-widget/issues/7#issuecomment-326978682). Grav caches "yourtheme.yaml" in the "user/config/themes/yourtheme.yaml" check to see if there are any difference from your current theme. Can you also please check you "site.yaml" in user/config to make sure
```yaml
widget:
    areas:
        -
            location: aside #or footer or default
```
exist in that file.

Let me work on it now. Thanks

**Comment by alexej-d** [comment]
@sojimaxi I never changed the area names so #7 does not apply to my case. The cached config is the same as in my theme.yaml. Thanks!

**Comment by sojimaxi** [comment]
okay. @alexej-d please can you confirm there is a
```yaml
widget:
    areas:
        -
            location: aside #or footer or default
```
field in your "site.yaml" and if possible let me know what you find.

**Comment by alexej-d** [comment]
@sojimaxi yes its is.

**Comment by SimpleByDesign** [comment]
Hi,

I think I may have a solution.

The issue appears to be in the widget.php file.

On line 309 you have: $wigs = (array) $headers->{self::KEY};

However $wigs on my system appears not to be set as an array when using only globals..

To fix the issue as a work around I did the following:

Added this on line 307:

`$page_has_widget = array_key_exists(self::KEY,$headers);`

Which is just before just the IF statement:

`if($has_widget && $rc_level++ <= self::MAX_RECURSE){`

Then replaced the following (line 309):

`$wigs = (array) $headers->{self::KEY};`

With:

```
if( $page_has_widget ){
  $wigs = (array) $headers->{self::KEY};
}else{
  $wigs = array();
}
```

My entire process function for the widget.php looks like this:

```
    public static function process($context, $area, $merge_global)
    {
        /**
         * This variable is meant to prevent indefinite recursive widgets;
         * in case if widgets in widget is enabled
         *  maximum allow nest 2;
        */
        static $rc_level=0;

        /* @var Page $page */
        $page = $context['page'];

        /* @var Config $config */
        $config = $context['config'];
        $global_widgets  = $config->get('site.widget',false);

        $headers = $page->header();
        $has_widget = array_key_exists(self::KEY,$headers);
        $content = '';
        $has_widget = $merge_global ? ($global_widgets || $has_widget): $has_widget;
        $page_has_widget = array_key_exists(self::KEY,$headers);
        if($has_widget && $rc_level++ <= self::MAX_RECURSE){
            if( $page_has_widget ){
              $wigs = (array) $headers->{self::KEY};
            }else{
              $wigs = array();
            }
            if($merge_global && $global_widgets){
                $wigs = $global_widgets ? array_merge_recursive($global_widgets,$wigs) : $wigs;

            }
            if($wigs){
                $locs =[];

                /* Fix empty call with widget('') instead of widget() */
                $area = empty($area)?'default':$area;
                if(isset($wigs['areas'])) { //prevent invalid argument for foreach
                    foreach ($wigs['areas'] as $idx => $node) {
                        $key = $node['location'];

                        /* Merge multiple area definition into one */
                        if (isset($node['widgets']))
                            $locs[$key] = isset($locs[$key]) ? array_merge($locs[$key], $node['widgets']) : $node['widgets'];
                    }
                }

                if(array_key_exists($area,$locs)){

                    foreach ($locs[$area] as $idx => $widget) {
                        $page_path = $widget['load'];
                        $enabled = $widget['enabled'];

                        if($enabled){
                            $inject = $page->find($page_path);
                            if ($inject) {

                                /**
                                 * Sometimes twig changes don't get picked up immediately you can force this
                                 * by temporarily disabling cache for the page
                                 */
//                                $inject->modifyHeader('cache_enable',false);
//                                $inject->modifyHeader('never_cache_twig',true);
                                $content .= $inject->content();

                            }
                        }
                    }
                }


            }
        }
        $rc_level--;

        return $content;
    }
```

With this code alteration my global widget now works without the need to add a widget holder on the page.

I hope this makes sense.

**Comment by sojimaxi** [comment]
@SimpleByDesign @alexej-d  I already push a new release. I found out where the problem was.

**Comment by sojimaxi** [comment]
@SimpleByDesign  yes that was the cause thanks a lot. Just came online now to post an update I was a little busy earlier and it seems you also found it. Thanks for the support.
